version: "3.3"
services:
  react-app:
    image: react-app
    build:
      context: ./client
      dockerfile: ./Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  node-app:
    image: node-app
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
